Youtube video page
mohapakram/youtube-clone pull request #4
Opened 2020-06-03 07:54 UTC by mohapakram

# What this branch has is a youtube video page with:

## Navigation bar
- It has an embedded image that represents a logo.
- The logo is aligned to the leftmost part of the navbar.
- It has an input tag that represents a search bar.
- The search bar is aligned to the middle of the navbar.
- It has a button tag that represents the search button.
- The search button is at the end (rightmost part) of the search bar.
- It has at least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar.

## Video
- It is displayed.
- It shows the video title.
- It shows the number of views.
- It has like and dislike icons.
- It has a share button.
- It shows the avatar of the user who uploaded the video.
- It has a subscribe button.

## Sidebar Recommended videos
- It shows the recommended video’s thumbnail preview (as image not as an actual video).
- It shows the title of the video.
- It shows the number of views.

2020-06-03 11:16 UTC, peterrobert commented
**PULL REQUEST UNDER REVIEW BY PETER ROBERT**

2020-06-03 12:01 UTC, peterrobert requested changes
**CHANGES REQUIRED** :stop_sign: 

Great work so far :clap:  But in order for me to approve this project you need to make the following changes

1. You need to fix all the conflicts between your branches.

2. You need to create your pull request messages like described [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

3. Remember to use <section> tag for your different sections in your webpage

4. Fix all HTML validation errors. You can validate your HTML [here](https://validator.w3.org/) 
![html](https://user-images.githubusercontent.com/32361963/83633746-1c893980-a5aa-11ea-86fe-f6f9a856cad1.jpg)

5. Fix the alignment of the UpNext column. The title and the text aren't properly aligned.
![allign](https://user-images.githubusercontent.com/32361963/83634203-cec10100-a5aa-11ea-9ab6-627829668ee0.jpg)

happy coding :computer:  and remember to submit another review once you fix all the recommended issues:smiley:

2020-06-03 12:01 UTC, peterrobert commented on Readme.md
Add more description to your readme file. You can use this [template](https://github.com/microverseinc/readme-template) to make your readme more descriptive

2020-06-03 12:01 UTC, peterrobert commented on index.html
> +            </div>
Kindly use buttons. It's okay to use font-awesome icons but you should make them clickable. You can do this by changing the cursor in your css

2020-06-03 13:36 UTC, mohapakram commented
@peterrobert hello peter,
We have only one conflict with the master branch and I don't think we can resolve it without merging the feature branch and the master branch, so when we get the pull request approved we will fix the conflict and merge.

If there is a way to fix the conflict without merging please let us know.

thank you for the awesome review!

2020-06-03 22:34 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-06-03 22:44 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @mohapakram and @OlawaleJoseph, great job :+1: We are almost there. Let us fix a few comments so we can approve the project. Kindly check comments below:
- The avatar is not positioned correctly, let us fix it. Screenshot below
![noww](https://user-images.githubusercontent.com/46388113/83696075-06e83400-a5eb-11ea-8f67-4d85fb441de5.png)
- The subscribe button should be a link
![ssb](https://user-images.githubusercontent.com/46388113/83696242-7827e700-a5eb-11ea-8679-42f9d834c428.png)

Kindly make these changes and submit another review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-06-04 20:32 UTC, BrittanyBlake approved these changes
### Status: Approved  ✅ 
****
### Hi @mohapakram and @OlawaleJoseph 👋 👋 
Great job implementing the requested changes! 👏 👏 👏  It's a 👍 from me!  
Go ahead and merge this pull request and keep up the good work 😄 

- Don't forget to resolve the conflicts before merging 😉 

Happy coding! 😄

2020-06-05 07:40 UTC, merged